# Generated by Django 3.2.5 on 2022-01-21 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, max_length=256, verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('vxnumber', models.CharField(blank=True, max_length=50, verbose_name='微信号')),
                ('qqnumber', models.CharField(blank=True, max_length=20, verbose_name='qq号')),
                ('phone_number', models.IntegerField(default=0, verbose_name='手机号')),
                ('area', models.CharField(max_length=10, verbose_name='所在省份')),
                ('education', models.CharField(choices=[('KI', '幼儿园'), ('PR', '小学'), ('JU', '初中'), ('FR', '高一'), ('SO', '高二'), ('SR', '高三')], default='KI', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
