# Generated by Django 3.2.5 on 2022-01-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuyaplat', '0003_alter_student_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qqnumber',
            new_name='qq_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='vxnumber',
            new_name='vx_number',
        ),
    ]
